# Generated by Django 2.2 on 2020-04-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_ticket_action_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
